language: csharp

os: linux
dist: trusty
sudo: required
dotnet: 2.0.0
mono: latest

script:
  - "cd ci-script"
  - "./build.sh -t NuGetPack"
  - "cd .."
  - "if [[ $TRAVIS_PULL_REQUEST == 'false' && $TRAVIS_TAG ]]; then 
  dotnet nuget push source/nupkg/*.nupkg -k $NUGET_API_KEY -s https://www.nuget.org/api/v2/package;
  fi"